config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_categories, only: [:index], path: 'products'
  resources :product_properties, only: [:index]
  resources :offers, only: [:index]
  resources :image_upload, only: [:new]
  resources :order_products, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create, :show]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_products
  monetize :total_amount_cents
  # before_create :set_order_status
  #before_save :update_total_amount

  def total_amount
    if order_products.any?
      order_products.collect { |order_product| order_product.price }.sum
    else
      Money.new(0, 'EUR')
    end
  end

  def total_amount_cents
    total_amount.fractional
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_total_amount
    self[:total_amount_cents] = total_amount
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :shop_product
  belongs_to :order
  mount_uploader :image, ImageUploader
  monetize :price_cents
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :shop_products
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
  has_many :product_properties
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product_category
  has_many :property_values
end

app/models/property_value.rb
class PropertyValue < ApplicationRecord
  belongs_to :product_property
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_products
end

app/models/shop_product.rb
class ShopProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  monetize :price_cents
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_products = @order.order_products
    pp @order_products
  end
end

app/controllers/image_upload_controller.rb
class ImageUploadController < ApplicationController
  def new
    @shop_product = get_shop_product
    @order_product = OrderProduct.new
  end

  def get_shop_product
    shop_product_params = params.require(:offer).permit(:id)
    ShopProduct.where(shop_product_params).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/image_upload_helper.rb
module ImageUploadHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, attr_hash)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: attr_hash[:class], id: attr_hash[:id],
      "data-toggle" => attr_hash["data-toggle"])
  end
end

app/views/image_upload/_image_upload_form.html.erb
<section id="image-upload-section">
  <div class="container">
    <h3 class="section-heading">Add a image file</h3>
    <div class="image-upload-form">
      <%= simple_form_for @order_product, url: order_products_path, method: :post  do |f| %>
        <%= f.input_field :image, input_html: { class: "btn btn-primary" } %>
        <%= f.input_field :image_cache, as: :hidden %>
        <%= f.hidden_field :id, value: @shop_product.id %>
        <div class="next-section-button">
          <span class="next-section-button-text">Next:</span>
          <%= f.submit "Add to cart", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/image_upload/new.js.erb
$( document ).ready(function() {
  $("#Site-content").fadeOut(500, function() {
    $("#Site-content").html("<%= escape_javascript(render('image_upload_form')) %>").hide();
    $("#Site-content").fadeIn(500);
  });
});