config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_categories, only: [:index], path: 'products'
  resources :product_properties, only: [:index]
  resources :offers, only: [:index]
  resources :image_upload, only: [:new]
  resources :order_products, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create, :show]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_products
  monetize :total_amount_cents
  # before_create :set_order_status
  #before_save :update_total_amount

  def total_amount
    if order_products.any?
      order_products.collect { |order_product| order_product.price }.sum
    else
      Money.new(0, 'EUR')
    end
  end

  def total_amount_cents
    total_amount.fractional
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_total_amount
    self[:total_amount_cents] = total_amount
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :shop_product
  belongs_to :order
  mount_uploader :image, ImageUploader
  monetize :price_cents
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :shop_products
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
  has_many :product_properties
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product_category
  has_many :property_values
end

app/models/property_value.rb
class PropertyValue < ApplicationRecord
  belongs_to :product_property
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_products
end

app/models/shop_product.rb
class ShopProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  monetize :price_cents
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/image_upload_helper.rb
module ImageUploadHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, attr_hash)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: attr_hash[:class], id: attr_hash[:id],
      "data-toggle" => attr_hash["data-toggle"])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeGraf | The Printplace</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body id="Site">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <main id="Site-content">
       <%= yield %>
    </main>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_features.html.erb
  <section id="features-section">
    <div class="container">
      <div class="feature-list">
        <div class="feature">
          <div class="feature-icon">
            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
          </div>
          <div class="feature-text">
            <h3>Simples</h3>
            <p>Escolha seus materiais, quantidade e tipos de acabamento.</p>
          </div>
        </div>
        <div class="feature">
          <div class="feature-icon">
           <i class="fa fa-check-square-o" aria-hidden="true"></i>
          </div>
          <div class="feature-text">
            <h3>Fácil</h3>
            <p>Compare ratings, prazos de entrega e preços das gráficas locais, em apenas um click!</p>
          </div>
        </div>
        <div class="feature">
          <div class="feature-icon">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </div>
          <div class="feature-text">
            <h3>Rápido</h3>
            <p>Pague no site, receba onde quiser.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/pages/_presentation.html.erb
<section id="presentation-section">
  <div class="container">
    <div class="presentation">
      <div class="presentation-text">
        <h1>BeGraf</h1>
        <h2>Ajuda-te a economizar tempo e dinheiro com comparações de
        gráficas locais para seus materiais impressos</h2>
        <div class="presentation-cta">
          <%= link_to "Start Using Now!", product_categories_path, remote: true, :class => "btn btn-primary" %>
        </div>
      </div>
      <div class="presentation-video">
        <div class="wistia_embed wistia_async_i5rq54jj3i" style="height:281px;width:500px">&nbsp;</div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_subscribe.html.erb
 <section id="subscribe-section">
  <div class="container">
    <div class="subscribe-wrapper">
      <div class="subscribe">
        <h3 class="subscribe-heading">Inscreva-se Ahora!</h3>
        <p class="subscribe-text">Deixe-nos o seu email e receba promoções exclusivas!</p>
        <form class="form-inline" id="subscribe-form">
          <div class="form-group">
            <input type="email" class="form-control" id="email" placeholder="Insira seu e-mail">
          </div>
          <button type="submit" class="btn btn-primary">Quero receber</button>
        </form>
        <h3 class="subscribe-heading">Aproveite. É grátis!</h3>
      </div>
    </div>
  </div>
 </section>

app/views/pages/home.html.erb
<div id="homepage">
  <%= render 'shared/header' %>
  <%= render 'features' %>
  <%= render 'subscribe' %>
</div>
<script src="https://fast.wistia.com/embed/medias/i5rq54jj3i.jsonp" async></script>
<script src="https://fast.wistia.com/assets/external/E-v1.js" async></script>

app/views/shared/_checkout_notify.html.erb
<% if current_order.order_products.any? %>
  <%= link_to "Checkout", new_payment_path, class: "btn btn-primary btn-xs" %>
<% end %>

app/views/shared/_flashes.html.erb
<div id="flash-messages">
  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
  <% if !flash.empty? %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <ul class="footer-nav">
    <li><%= link_to "Home", "#" %></li>
    <li><%= link_to "About", "#" %></li>
    <li><%= link_to "Market", "#" %></li>
  </ul>
  <p class="footer-copyright">&copy; BeGraf 2017. All Rights Reserved</p>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="container header-home">
        <!-- Start Row -->
        <div class="row">
            <div class="col-sm-6 header-text">
                <h1>BeGraf</h1>
                <h2 class="lead">Ajuda-te a economizar tempo e dinheiro com comparações de gráficas locais para seus materiais impressos</h2>
                <div class="row">
                    <div class="col-sm-5 col-xs-12 header-cta col-centered">
                        <%= link_to "Comece a comprar!", product_categories_path, remote: true, :class => "btn btn-lg btn-begraf" %>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 col-sm-offset-1">
                <!-- <img class="img-rounded img-responsive" src="banner_image.png"> -->
                <%= image_tag "banner_image.png", class: " img-responsive img-banner" %>
            </div>
        </div>
        <!--// END Row -->
    </div>
</header> 

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <div id="shopping-cart-notify" style="margin-right: 10px;">
        <%= render 'shared/shopping_cart_notify' %>
      </div>

      <div id="checkout-notify" style="margin-right: 20px;">
        <%= render 'shared/checkout_notify' %>
      </div>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= gravatar_for(current_user,
          class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_shopping_cart_notify.html.erb
<%= link_to cart_path, class: "navbar-wagon-item navbar-wagon-link" do %>
  <div class="badge-container">
    <i class="fa fa-shopping-cart"></i>
    <div class="badge badge-blue"><%= current_order.order_products.size %></div>
  </div>
<% end %>