config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_categories, only: [:index], path: 'products'
  resources :product_properties, only: [:index]
  resources :offers, only: [:index]
  resources :image_upload, only: [:new]
  resources :order_products, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create, :show]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_products
  monetize :total_amount_cents
  # before_create :set_order_status
  #before_save :update_total_amount

  def total_amount
    if order_products.any?
      order_products.collect { |order_product| order_product.price }.sum
    else
      Money.new(0, 'EUR')
    end
  end

  def total_amount_cents
    total_amount.fractional
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_total_amount
    self[:total_amount_cents] = total_amount
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :shop_product
  belongs_to :order
  mount_uploader :image, ImageUploader
  monetize :price_cents
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :shop_products
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
  has_many :product_properties
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product_category
  has_many :property_values
end

app/models/property_value.rb
class PropertyValue < ApplicationRecord
  belongs_to :product_property
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_products
end

app/models/shop_product.rb
class ShopProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  monetize :price_cents
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_products = @order.order_products
    pp @order_products
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new

  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.total_amount_cents, # or amount_pennies
      description:  "Payment for order #{@order.id}",
      currency:     @order.total_amount.currency
    )

    @order.update(payment: charge.to_json, order_status_id: 2)
    redirect_to payment_path(@order.id)


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path
  end

  def show
    @order = Order.where(order_status_id: 2).find(params[:id])
  end

  private

  def set_order
    @order = current_order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/image_upload_helper.rb
module ImageUploadHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, attr_hash)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: attr_hash[:class], id: attr_hash[:id],
      "data-toggle" => attr_hash["data-toggle"])
  end
end

app/views/payments/new.html.erb
<div class="container">
  <h2>Your purchase</h2>

<%= form_tag payments_path do %>
  <table class="checkout-product-list" style="margin-bottom: 40px;">
    <tr>
      <th>Product</th>
      <th>Shop</th>
      <th>price</th>
      <th>Delivery</th>
    </tr>
    <% @order.order_products.each do |order_product| %>
      <tr>
        <td><%= order_product.shop_product.product.product_category.name %></td>
        <td><%= order_product.shop_product.shop.name %></td>
        <td><%= humanized_money_with_symbol(order_product.shop_product.price) %></td>
        <td>
            <%= order_product.shop_product.delivery_days %>
            <%= "day".pluralize(order_product.shop_product.delivery_days) %>
        </td>
      </tr>
    <% end %>
    <tr>
    </tr>
  </table>

  <div style="display: flex; justify-content: center;align-items: center;">
    <div class="checkout-total" style="margin-right: 20px; font-size: 22px;">
     Total amount: <%= humanized_money_with_symbol(@order.total_amount) %>
   </div>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="BeGraf Print Marketplace"
      data-email="<%= current_user.email %>"
      data-description="Order ID: #<%= @order.id%>"
      data-amount="<%= @order.total_amount_cents %>"
      data-currency="<%= @order.total_amount.currency %>">
    </script>
  </div>


<% end %>
</div>

app/views/payments/show.html.erb
<h1>Payment confirmation</h1>
<p>Order ID: #<%= @order.id %></p>
<p>Order status: <%= @order.order_status.name %></p>
<p>Order customer: <%= @order.user.email %></p>
<p>Order total amount: <%= humanized_money_with_symbol(@order.total_amount) %></p>