config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_categories, only: [:index], path: 'products'
  resources :product_properties, only: [:index]
  resources :offers, only: [:index]
  resources :image_upload, only: [:new]
  resources :order_products, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :payments, only: [:new, :create, :show]
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_products
  monetize :total_amount_cents
  # before_create :set_order_status
  #before_save :update_total_amount

  def total_amount
    if order_products.any?
      order_products.collect { |order_product| order_product.price }.sum
    else
      Money.new(0, 'EUR')
    end
  end

  def total_amount_cents
    total_amount.fractional
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_total_amount
    self[:total_amount_cents] = total_amount
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :shop_product
  belongs_to :order
  mount_uploader :image, ImageUploader
  monetize :price_cents
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :shop_products
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
  has_many :product_properties
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product_category
  has_many :property_values
end

app/models/property_value.rb
class PropertyValue < ApplicationRecord
  belongs_to :product_property
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_products
end

app/models/shop_product.rb
class ShopProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
  monetize :price_cents
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_products = @order.order_products
    pp @order_products
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @product = Product.where(product_params).first
    @offers = ShopProduct.where(product: @product)
  end

  def product_params
    formatted_params = params.require(:product).permit(:format, :print_mode, :paper_type, :quantity, :print_finish)
    formatted_params[:quantity] = formatted_params[:quantity].to_i
    formatted_params
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/image_upload_helper.rb
module ImageUploadHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, attr_hash)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: attr_hash[:class], id: attr_hash[:id],
      "data-toggle" => attr_hash["data-toggle"])
  end
end

app/views/offers/_product_offer_list.html.erb
<h3 class="offers-list-pres">Choose one of the offers:</h3>

<%= form_tag "/order_products", remote: true do %>
  <div class="offer-list">
    <% @offers.each do |offer| %>
      <div class="offer">
        <h4><%= offer.shop.name %></h4>
        <p>Price: <%= offer.price %> &euro;</p>
        <p><%= offer.delivery_days %> delivery days</p>
        <input type="radio" name="offer[id]" value="<%= offer.id %>" >
      </div>
    <% end %>
  </div>
  <div style="display:flex; justify-content: center; margin: 40px 0;">
    <input type="submit" value="Add to cart" class="btn btn-primary">
  </div>
<% end %>

app/views/offers/_product_offers.html.erb
<section id="product-offers-section">
  <div class="container">
    <h3 class="section-heading">Choose one of the offers:</h3>
    <%= form_tag new_image_upload_path, method: 'get', remote: true do %>
      <div class="offer-list">
        <% @offers.each do |offer| %>
          <div class="offer">
            <div class="offer-check-icon">
              <i class="fa fa-check-circle" aria-hidden="true"></i>
            </div>
            <h4 class="offer-shop"><%= offer.shop.name %></h4>
            <div class="offer-shop-rating">
              <% offer.shop.rating.floor.times do %>
                <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
              <% (5 - offer.shop.rating.floor).times do %>
                <i class="fa fa-star-o" aria-hidden="true"></i>
              <% end %>
            </div>
            <p class="offer-price"><%= humanized_money_with_symbol(offer.price) %></p>
            <p class="offer-delivery">Delivery in <%= pluralize(offer.delivery_days, 'day') %></p>
            <input type="radio" name="offer[id]" value="<%= offer.id %>" >
          </div>
        <% end %>
      </div>
      <div class="next-section-button">
        <span class="next-section-button-text">Next:</span>
        <input id="upload-image-button" type="submit" value="Add an image file" class="btn btn-primary">
      </div>
    <% end %>
  </div>
</section>

app/views/offers/find_offers.js.erb
$("#product-offers").html("");
$("#image-upload-form").html("");
$("#product-offers").html("<%= escape_javascript(render('product_offers')) %>");
$('html, body').animate({
  scrollTop: $("#product-offers").offset().top
 }, 1000);

$("#product-find-button").hide();

$(".offer").click( function(event) {
  var offer = event.currentTarget;
  $(offer).siblings().removeClass("offer-selected");
  $(offer).addClass("offer-selected");
  $(offer).find("input[type=radio]").prop("checked", true);
});

app/views/offers/index.js.erb
$( document ).ready(function() {
  $("#Site-content").fadeOut(500, function() {
    $("#Site-content").html("<%= escape_javascript(render('product_offers')) %>").hide();
    $("#Site-content").fadeIn(500);
    $(".next-section-button").hide();

    $(".offer").click( function(event) {
      var offer = event.currentTarget;
      $(offer).siblings().removeClass("offer-selected");
      $(offer).addClass("offer-selected");
      $(offer).find("input[type=radio]").prop("checked", true);
      $(".next-section-button").fadeIn(1000);
    });
  });
});